# coding: utf-8

"""
    Chatbot API with Google Authentication

    An API for interacting with our chatbot, providing feedback, and managing sessions.  # noqa: E501

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_callback_get(self):
        """Test case for auth_callback_get

        Callback endpoint for Google's OAuth 2.0 authentication  # noqa: E501
        """
        pass

    def test_chat_post(self):
        """Test case for chat_post

        Send a question to the chatbot  # noqa: E501
        """
        pass

    def test_chat_response_id_result_get(self):
        """Test case for chat_response_id_result_get

        Poll for the chatbot's response using the responseID  # noqa: E501
        """
        pass

    def test_feedback_post(self):
        """Test case for feedback_post

        Provide feedback on the chatbot's response  # noqa: E501
        """
        pass

    def test_login_get(self):
        """Test case for login_get

        Redirect to Google's OAuth 2.0 authentication  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
