# coding: utf-8

"""
    Chatbot API with Google Authentication

    An API for interacting with our chatbot, providing feedback, and managing sessions.  # noqa: E501

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_info_response import UserInfoResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestUserInfoResponse(unittest.TestCase):
    """UserInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserInfoResponse(self):
        """Test UserInfoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_info_response.UserInfoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
